<a href="https://colab.research.google.com/github/nicePaul521/ML/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.如何构建numpy数组

In [0]:
import numpy as np
#t通过列表创建一维数组
list1 = [0,1,2,3,4]
arrld = np.array(list1)
print(type(arrld))#打印类型
arrld

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

数组是基于向量化操作的，在实际的项目处理中，处理的数据结构一般是矩阵结构，函数可以引用带数组的每一项，而列表不行。

In [0]:
#numpy可以通过列表中的中的列表来创建二维数组
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

可以通过dtype参数来指定数组类型，一般常用的numpy类型是：float,int,bool,str,object.

In [0]:
arr2d_f = np.array(list2,dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

也可以通过astype方法转换成不同的类型

In [0]:
#转换成int类型,在转换成str类型
arr2d_f.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U21')

数组要求所有项时同一个类型，list没有这个限制，如果让一个数组包含不同类型，设置dtype为object

In [0]:
arr2d_b = np.array([1,0,10],dtype='bool')#构建布尔类型数组
print(arr2d_b)
#构建包含数值和字符串的数组
arr1d_obj = np.array([1,'a'],dtype='object')
arr1d_obj


[ True False  True]


array([1, 'a'], dtype=object)

使用tolist（）函数使数组转为列表

In [0]:
arr1d_obj.tolist()

[1, 'a']

数组与列表的区别：


1.   数组支持向量化操作，列表不支持
2.   数组不能改变长度，列表可以
3.   数组每一项都是同种类型，列表有多种类型
4.   同样长度的数组所占的空间小于列表



## 2.如何观察数组属性的大小与形状

数组的属性包括：
*   数组的维度（ndim）
*   数组的形状（shape）
*   数组的类型（dtype）

*   数组的大小（size）





In [0]:
#定义3行4列的二维数组
list2 = [[1,2,3,4],[3,4,5,6],[5,6,7,8]]
arr2 = np.array(list2,dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [0]:
#形状（shape）
print('Shape:',arr2.shape)
#数组类型（dtype）
print('Datatype:',arr2.dtype)
#数组大小（size）
print('Size:',arr2.size)
#数组维度
print('Num Dimensions:',arr2.ndim)
#数组的第三行三列元素
print('item of 3 line 3 column:',arr2[2,2])

Shape: (3, 4)
Datatype: float64
Size: 12
Num Dimensions: 2
item of 3 line 3 column: 7.0


## 3.如何从数组中提取特定项

数组的索引是从0开始计数，与list类似，numpy数组通过方括号的参数以选择特定的元素



In [0]:
#选择矩阵的前两行，两列
arr2[:2,:2]

array([[1., 2.],
       [3., 4.]])

布尔类型的数组与过滤前的数组大小相等，布尔类型数组只包含True和False变量，True变量对应的数组索引位置保留了过滤前的值

In [0]:
#对数组的每一元素是否满足某一条件，然后获取布尔类型的输出
b = arr2>4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [0]:
#取布尔型数组保留的原始数组的值,即是过滤后的数组
arr2[b]

array([5., 6., 5., 6., 7., 8.])

数组的反转

In [0]:
#反转数组的行
arr2[::-1,]

array([[5., 6., 7., 8.],
       [3., 4., 5., 6.],
       [1., 2., 3., 4.]])

In [0]:
#反转数组的行和列
arr2[::-1,::-1]

array([[8., 7., 6., 5.],
       [6., 5., 4., 3.],
       [4., 3., 2., 1.]])

处理缺失值和无穷大值，缺失值可以用np.nan对象表示，np.inf表示无穷大值

In [0]:
#插入nan变量和inf变量
arr2[1,1] = np.nan
arr2[1,2] = np.inf
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [0]:
#使用-1代替nan和inf值
missing_bool = np.isnan(arr2)|np.isinf(arr2)
arr2[missing_bool] = -1
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [0]:
#求平均值，最大值，最小值
print("Mean value is: ",arr2.mean())
print("Max value is: ",arr2.max())
print("Min value is: ",arr2.min())

Mean value is:  3.5833333333333335
Max value is:  8.0
Min value is:  -1.0


In [0]:
#求数组行和列的最小值
#axis=0表示列，1表示行
print("Column wiser minimum: ",np.amin(arr2,axis=0))
print("Row wiser minimum: ",np.amin(arr2,axis=1))

Column wiser minimum:  [ 1. -1. -1.  4.]
Row wiser minimum:  [ 1. -1.  5.]


In [0]:
#对数组元素进行累加，得到一维数组，一维数组的大小与二维数组相同
np.cumsum(arr2)

array([ 1.,  3.,  6., 10., 13., 12., 11., 17., 22., 28., 35., 43.])

## 4.如何从现有的数组定义新数组

如果使用赋值运算符从父数组定义新数组，新数组与父数组公用一个存储空间，如果改变新数组的值，父数组也相应的改变，为了让新数组与父数组相互独立，需要使用copy函数，所有的父数组都使用copy（）方法构建新数组。

In [0]:
#分配arr2数组给新数组arr2a，下面的方法没有定义新数组
arr2a = arr2[:2,:2]
arr2a[1,1] = 100#arr2相应位置也改变了
arr2

array([[  1.,   2.,   3.,   4.],
       [  3., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [0]:
#赋值arr2数组的一部分给新数组arr2b
arr2b = arr2[:2,:2].copy()
arr2b[1,1] = 101#arr2没有改变
arr2

array([[  1.,   2.,   3.,   4.],
       [  3., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

## 5.多维数组的重构(reshaping)与扁平(flattening)

重构是为了改变数组项的排列，即改变数组的形状，未改变数组的维数。
扁平是对多维数组转化为一维数组。

In [0]:
#3x4数组重构为4x3数组
arr2.reshape(4,3)

array([[  1.,   2.,   3.],
       [  4.,   3., 100.],
       [ -1.,   6.,   5.],
       [  6.,   7.,   8.]])

In [0]:
arr2.flatten()

array([  1.,   2.,   3.,   4.,   3., 100.,  -1.,   6.,   5.,   6.,   7.,
         8.])

array([  1.,   2.,   3.,   4.,   3., 100.,  -1.,   6.,   5.,   6.,   7.,
         8.])

In [0]:
#flatten处理后的数组是父数组的引用，因此新数组的任何改变都会影响父数组
b1 = arr2.flatten()
b1[0] = 100#改变b1的值并未影响arr2
arr2

array([[  1.,   2.,   3.,   4.],
       [  3., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [0]:
#ravel使用复制的方式构建新数组
b2 = arr2.ravel()
b2[0] = 101#改变b2的值，相应改变了arr2的值
arr2

array([[101.,   2.,   3.,   4.],
       [  3., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

## 6.如何numpy生成序列数，重复数和随机数

np.arange()函数手动生成指定数目的随机数

In [0]:
#默认下限为0
print(np.arange(5))

#0 to 9,默认步数为1
print(np.arange(0,10))

#递增步数为2
print(np.arange(0,10,2))

#降序
print(np.arange(10,0,-1))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]


上述是通过设置初始位置和结束位置来生成序列数，如果我们设置数组的元素个数，那么可以自动计算数组递增值。

In [0]:
np.linspace(start=1,stop=50,num=10,dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

上面例子的递增值并不相同，有5，6值，原因是递增值采用了四舍五入的算法，np.logspace以对数的方式增长

In [0]:
#设置数组的精度为小数点后两位
np.set_printoptions(precision=2)
#起点为10^1，终点为10^50，数组元素个数为10，以10为底数
np.logspace(start=1,stop=50,num=10,base=10)

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [0]:
#构建重复序列数
#np.tile重复整个数组或列表n次，np.repeat重复数组每一项n次
a = [1,2,3]
#重复数组a两次
print('title: ',np.tile(a,2))
#重复数组a每项两次
print('repeat: ',np.repeat(a,2))

title:  [1 2 3 1 2 3]
repeat:  [1 1 2 2 3 3]


生成随机数：random模块包含的函数可以生成任一数组形状的随机数和统计分布

In [0]:
#生成2*2的[0,1)的随机数
print(np.random.rand(2,2))

#生成均值标准正态分布的2*2的随机数
print(np.random.randn(2,2))

#生成[0,10)的2行2列的随机整数
print(np.random.randint(0,10,size=[2,2]))

#生成一个[0,1)的随机数
print(np.random.random())

#生成[0,1)2行2列的随机数
print(np.random.random(size=[2,2]))
 
#从给定列表等概率抽样10次
print(np.random.choice(['a','e','i','o','u'],size=10))

#从给定的列表和对应的概率分布抽样10次
print(np.random.choice(['a','e','i','o','u'],size=10,p=[0.3,.1,.1,.4,.1]))

[[0.83 0.34]
 [0.55 0.88]]
[[-0.18  1.2 ]
 [-0.47  0.63]]
[[0 0]
 [6 9]]
0.5028929675761946
[[0.18 0.58]
 [0.92 0.84]]
['a' 'i' 'o' 'o' 'a' 'i' 'u' 'u' 'a' 'o']
['a' 'i' 'a' 'a' 'o' 'o' 'o' 'o' 'e' 'a']


得到数组独特项与个数：np.unique函数去除数组中重复的元素，设置return_counts参数为True，得到数组每一项的个数。

In [0]:
#定义范围为[0,10)，个数为10的随机整数数组
np.random.seed(100)
arr_rand = np.random.randint(0,10,size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [0]:
#得到数组独特的项和对应的个数
uniqs,counts = np.unique(arr_rand,return_counts=True)
print("Unique itms: ",uniqs)
print("Counts ",counts)

Unique itms:  [0 2 3 4 5 7 8]
Counts  [1 2 1 1 1 2 2]


## 7.如何获取满足条设条件的索引

In [0]:
import numpy as np
arr_rand = np.array([8,8,3,7,7,0,4,2,5,2])
#根据数组元素是否>4，满足为True，反之为False
b = arr_rand>4
b

array([ True,  True, False,  True,  True, False, False, False,  True,
       False])

In [0]:
#得到满足条件的索引，用np.where函数实现
#定位数组大于5的索引
index_gt5 = np.where(arr_rand>5)
print("Position where value > 5: ",index_gt5)

Position where value > 5:  (array([0, 1, 3, 4]),)


np.where也可以接受另外两个可选择参数x,y。当条件满足时，输出x，反之输出y

In [0]:
#如果值大于5，输出字符串'gt5'，反之输出'1e5'
np.where(arr_rand>5,'gt5','le5')

array(['gt5', 'gt5', 'le5', 'gt5', 'gt5', 'le5', 'le5', 'le5', 'le5',
       'le5'], dtype='<U3')

In [0]:
#np.argmax和np.argmin分别获取数组的最大值和最小值的索引
#最大值索引
print("Position of max value: ",np.argmax(arr_rand))

#最小值索引
print("Position of min value: ",np.argmin(arr_rand))

Position of max value:  0
Position of min value:  5


## 8.将数据导入和导出csv文件

In [0]:
#关闭数字的科学表示法
np.set_printoptions(suppress=True)
#从url的csv文件导入数据
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
#delimiter:分隔符，skip_header:从多少行开始读数据，以0开始，filling_values:缺失值表示，dtype：数据类型
data = np.genfromtxt(path,delimiter=',',skip_header=1,filling_values=-999,dtype='float')
data[:3]#显示前3行数据

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
        -999. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
        -999. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
        -999. ]])

In [0]:
#若设置参数dtype为'object'或'None',np.genformtxt在未设置占位的情况下能同时处理具有数字和文本的数据集
data2 = np.genfromtxt(path,delimiter=',',skip_header=1,dtype=None)
data2[:3]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', 'S38')])

In [0]:
#保存数据为csv文件
np.savetxt("out.csv",data,delimiter=',')

## 9.如何保存和加载numpy数据

Numpy提供了.npy和.npz文件类型来实现。如果保存一个ndarry数据，使用np.save保存为.npy;若保存多个ndarry数据，使用np.savez保存为.npz文件。加载numpy数据，统一使用np.load函数

In [0]:
#保存单一的numpy数据，使用.npy文件
arr2d = np.array([0,1,2])
np.save('myarray.npy',arr2d)
#保存多个numpy数据，使用.npz文件
arr2d_f = np.arange(5)
arr2d_b = np.arange(0,10,2)
np.savez('array.npz',arr2d_f,arr2d_b)
#加载.npz文件
a = np.load('myarray.npy')
print(a)

[0 1 2]


In [0]:
#加载.npz文件
b = np.load('array.npz')
print(b.files)#打印文件列表
b['arr_0']#打印文件中元素

['arr_0', 'arr_1']


array([0, 1, 2, 3, 4])

## 10.如何按列或行拼接numpy数组

1.设置np.concatenate参数axis的值为1或0，实现数组的列拼接或行拼接

2.np.vstack和np.hstack

3.np_r和np.c

In [0]:
#定义两个拼接的数组
a = np.zeros([4,4])
b = np.ones([4,4])
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [0]:
#行拼接数组
np.concatenate([a,b],axis=0)
np.vstack([a,b])
np.r_[a,b]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
#列拼接数组
np.concatenate([a,b],axis=1)
np.hstack([a,b])
np.c_[a,b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

## 11.如何对按列对数组排序

In [0]:
#生成随机矩阵
import numpy as np
arr = np.random.randint(1,6,size=[8,4])
arr

array([[2, 3, 5, 5],
       [2, 3, 1, 2],
       [4, 1, 1, 1],
       [4, 2, 4, 3],
       [4, 5, 1, 4],
       [5, 5, 1, 3],
       [3, 3, 2, 4],
       [4, 1, 2, 2]])

In [0]:
#np.sort基于列对arr排序
#axis=0,表示列排序，1表示行排序
np.sort(arr,axis=0)

array([[2, 1, 1, 1],
       [2, 1, 1, 2],
       [3, 2, 1, 2],
       [4, 3, 1, 3],
       [4, 3, 2, 3],
       [4, 3, 2, 4],
       [4, 5, 4, 4],
       [5, 5, 5, 5]])

np.sort排序函数默认所有列是相互独立的，对所有列进行排序，破坏了每行的结构，使用np.argsort函数可以保留行的完整性。

In [0]:
#对arr的第一列进行排序，返回索引
sorted_index_lstcol = arr[:,0].argsort()
#根据第一列的索引对数组排序，保留了行的完整性
arr[sorted_index_lstcol]

array([[2, 3, 5, 5],
       [2, 3, 1, 2],
       [3, 3, 2, 4],
       [4, 1, 1, 1],
       [4, 2, 4, 3],
       [4, 5, 1, 4],
       [4, 1, 2, 2],
       [5, 5, 1, 3]])

In [0]:
#倒转argsort索引实现递减排序
arr[sorted_index_lstcol[::-1]]

array([[5, 5, 1, 3],
       [4, 1, 2, 2],
       [4, 5, 1, 4],
       [4, 2, 4, 3],
       [4, 1, 1, 1],
       [3, 3, 2, 4],
       [2, 3, 1, 2],
       [2, 3, 5, 5]])

若要基于多个列对数组排序，使用np.lexsort函数，它的参数是元组类型，元组的每个元素表示数组的某一列，排序规则是：越靠近右边的列，优先级越高。

In [0]:
#先比较第一列，第一列相同的情况下再比较第二列
lexsorted_index = np.lexsort(arr[:,1],arr[:,0])
arr[lexsorted_index]

## 12.如何使用Numpy处理日期

np.datatime64创建日期对象，精确度达到纳秒，可以使用标准的YYYY-MM-DD格式字符串作为参数创建日期

In [0]:
#创建datetime64对象
date64 = np.datetime64('2018-02-04 23:10:10')
date64

numpy.datetime64('2018-02-04T23:10:10')

In [0]:
#从datetime64对象分离时间
dt64 = np.datetime64(date64,'D')#将日期分离
dt64

numpy.datetime64('2018-02-04')

如果想增加天数或其他任何时间单元，使用np.timedetlta函数非常方便

In [0]:
#np.delta建立多个时间单元
tenminutes = np.timedelta64(10,'m')#10分钟
tenseconds = np.timedelta64(10,'s')#10秒钟
tennanoseconds = np.timedelta64(10,'ns')#10纳秒

print('Add 10 days: ',dt64+10)#增加10t天
print("Add 10 minutes: ",dt64+tenminutes)#增加10分钟
print("Add 10 seconds: ",dt64+tenseconds)#增加10秒
print("Add 10 nanoseconds: ",dt64+tennanoseconds)#增加10纳秒

Add 10 days:  2018-02-14
Add 10 minutes:  2018-02-04T00:10
Add 10 seconds:  2018-02-04T00:00:10
Add 10 nanoseconds:  2018-02-04T00:00:00.000000010


In [0]:
#dt64转化为字符串
np.datetime_as_string(dt64)

'2018-02-04'

In [0]:
#np.is_busyday函数判断是否为工作日，工作日默认为周一到周日
print("Date: ",dt64)
print("Is it a business day?: ",np.is_busday(dt64))

Date:  2018-02-04
Is it a business day?:  False


In [0]:
#创建日期序列
dates = np.arange(np.datetime64('2018-02-01'),np.datetime64('2018-02-10'))
print(dates)
#检查是否是工作日
np.is_busday(dates)

['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09']


array([ True,  True, False, False,  True,  True,  True,  True,  True])

In [0]:
#np.datetime64类型转化为datetime.datetime类型
import datetime
dt = dt64.tolist()
dt

datetime.date(2018, 2, 4)

In [0]:
#获取datetime对象的年月日非常简便
print('Year: ',dt.year)
print('Day of month: ',dt.day)
print('Month of year: ',dt.month)
print('Day of week: ',dt.weekday())

Year:  2018
Day of month:  4
Month of year:  2
Day of week:  6


## 13.高阶numpy函数介绍

In [0]:
#标量函数只能处理标量，不能处理数组
#定义标量函数
def foo(x):
    if x%2 == 1:
        return x**2
    else:
        return x/2
print('x = 10 return ',foo(10))
print('x = 11 return ',foo(11))
#函数不能处理数组
#print(foo([10,11,12]))错误

x = 10 return  5.0
x = 11 return  121


np.vectorize使标量函数也能处理数组，可选otype为输出的类型

In [0]:
#函数向量化，向量化的输出类型是float
foo_v = np.vectorize(foo,otypes=[float])
print('x = [10,11,12] returns ',foo_v([10,11,12]))
print('x = [[10,11,12],[1,2,3]] returns ',foo_v([[10,11,12],[1,2,3]]))

x = [10,11,12] returns  [  5. 121.   6.]
x = [[10,11,12],[1,2,3]] returns  [[  5. 121.   6.]
 [  1.   1.   9.]]


如果要找数组每行或每列的最大值，numpy的一个特点是基于向量化操作的，因此我们可以使用np.apply_along_axis函数找每行或每列的最大值。

In [0]:
#定义一个4*10的随机二维数组
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [0]:
#基于列操作，找每列的最大值
print("max of per column: ",np.apply_along_axis(np.max,0,arr=arr_x))
#基于行操作，找每行的最大值
print('max of per row: ',np.apply_along_axis(np.max,1,arr=arr_x))

max of per column:  [9 9 4 8 9 6 9 7 6 8]
max of per row:  [9 9 8 9]


np.clip函数将数字限制在给定的截止范围，所有小于范围下限的数被当成下限值，大于范围上限的数被当成上限值。

In [0]:
#限制x的所有元素位于3和8之间
x = np.arange(10)
np.clip(x,3,8)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 8])

np.bincount函数统计从最小值到最大值的个数，最小值为0

In [0]:
x = np.array([1,1,2,3,2,4,4,5,6,6,6])
np.bincount(x)#计算出各个值出现的频数，0->0,1->2,2->2,3->1...

array([0, 2, 2, 1, 2, 1, 3])

np.histogram函数统计数据落入bins的区间，不考虑bins两侧的区间

In [0]:
x = np.array([1,1,2,3,2,4,4,5,6,6,6])
counts,bins = np.histogram(x,[0,2,4,6,8])
print('Counts: ',counts)
print('Bins: ',bins)

Counts:  [2 3 3 3]
Bins:  [0 2 4 6 8]
